### ISSUE TITLE
Client cannot send a deadline

### ISSUE THREAD

**Issue by dimi-nk** [bloomrpc/bloomrpc#129]
I'm making a call to a service with a deadline. I'm trying to find a way to pass the deadline but all I get is

```json
{
  "error": "10 ABORTED: No deadline specified"
}
```

I'm passing the following block in metadata, but it doesn't seem to work.

```json
{
    "deadline": "1570191247"
}
```

Any ideas?

**Comment by fenos** [comment]
Thanks for reporting this, it's seem currently not supported but i'll look into it

**Comment by fenos** [comment]
@dimi-nk did you try using an `int` data type instead of string?

**Comment by dimi-nk** [comment]
@fenos 
![image](https://user-images.githubusercontent.com/2273840/66786518-85675880-eed8-11e9-88d3-486991ccb9ad.png)

**Comment by fenos** [comment]
@dimi-nk this is fixed in the new release that hasn't been published just yet. Will be released this week

**Comment by dimi-nk** [comment]
@fenos thanks for the update!

**Comment by liufuyang** [comment]
@fenos Is this fixed? I am on 1.4.1 and it seems still have this issue dimi-nk pointed out above?

**Comment by Xiot** [comment]
I'm still seeing this as well

**Comment by bayucandra** [comment]
> @fenos
> ![image](https://user-images.githubusercontent.com/2273840/66786518-85675880-eed8-11e9-88d3-486991ccb9ad.png)

Same problem as this one

**Comment by jackielii** [comment]
grpc-web works with "deadline" but confirmed this is still a bug

**Comment by mariorez** [comment]
Try this way inside **METADATA** tab:
```
{
    "grpc-timeout": "1000m"
}
```
I could see in the server-side logs that "timeout" is propagated in subsequents gRPC calls.
See more: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

**Comment by dimi-nk** [comment]
@mariorez thanks! my client seems to hang though. Not sure if it's our gRPC server's issue or bloomRPC
